import type { SocialPlatform } from '@/types';

export const SOCIAL_PLATFORMS: SocialPlatform[] = [
  { id: 'whatsapp', name: 'WhatsApp', icon: '💬', color: '#25D366', bgColor: '#dcfce7', baseUrl: 'https://wa.me/', placeholder: '+92XXXXXXXXXX' },
  { id: 'facebook', name: 'Facebook', icon: '📘', color: '#1877F2', bgColor: '#dbeafe', baseUrl: 'https://facebook.com/', placeholder: 'username' },
  { id: 'instagram', name: 'Instagram', icon: '📷', color: '#E4405F', bgColor: '#fce7f3', baseUrl: 'https://instagram.com/', placeholder: '@username' },
  { id: 'tiktok', name: 'TikTok', icon: '🎵', color: '#000000', bgColor: '#f3f4f6', baseUrl: 'https://tiktok.com/@', placeholder: '@username' },
  { id: 'youtube', name: 'YouTube', icon: '▶️', color: '#FF0000', bgColor: '#fee2e2', baseUrl: 'https://youtube.com/', placeholder: '@channel' },
  { id: 'twitter', name: 'Twitter/X', icon: '🐦', color: '#1DA1F2', bgColor: '#e0f2fe', baseUrl: 'https://twitter.com/', placeholder: '@handle' },
  { id: 'linkedin', name: 'LinkedIn', icon: '💼', color: '#0A66C2', bgColor: '#dbeafe', baseUrl: 'https://linkedin.com/in/', placeholder: 'profile' },
  { id: 'telegram', name: 'Telegram', icon: '✈️', color: '#26A5E4', bgColor: '#e0f2fe', baseUrl: 'https://t.me/', placeholder: '@channel' },
  { id: 'snapchat', name: 'Snapchat', icon: '👻', color: '#FFFC00', bgColor: '#fefce8', baseUrl: 'https://snapchat.com/add/', placeholder: 'username' },
  { id: 'pinterest', name: 'Pinterest', icon: '📌', color: '#E60023', bgColor: '#fee2e2', baseUrl: 'https://pinterest.com/', placeholder: 'username' },
  { id: 'discord', name: 'Discord', icon: '🎮', color: '#5865F2', bgColor: '#ede9fe', baseUrl: 'https://discord.gg/', placeholder: 'invite code' },
  { id: 'reddit', name: 'Reddit', icon: '🤖', color: '#FF4500', bgColor: '#fed7aa', baseUrl: 'https://reddit.com/r/', placeholder: 'subreddit' },
  { id: 'wechat', name: 'WeChat', icon: '💚', color: '#07C160', bgColor: '#dcfce7', baseUrl: 'weixin://', placeholder: 'ID' },
  { id: 'viber', name: 'Viber', icon: '📞', color: '#7360F2', bgColor: '#ede9fe', baseUrl: 'viber://chat?number=', placeholder: '+number' },
  { id: 'signal', name: 'Signal', icon: '🔒', color: '#3A76F0', bgColor: '#dbeafe', baseUrl: 'https://signal.me/', placeholder: 'username' },
  { id: 'imo', name: 'IMO', icon: '💙', color: '#0077FF', bgColor: '#dbeafe', baseUrl: 'https://imo.im/', placeholder: 'ID' },
  { id: 'zoom', name: 'Zoom', icon: '🖥️', color: '#2D8CFF', bgColor: '#dbeafe', baseUrl: 'https://zoom.us/j/', placeholder: 'meeting ID' },
  { id: 'skype', name: 'Skype', icon: '📹', color: '#00AFF0', bgColor: '#e0f2fe', baseUrl: 'skype:', placeholder: 'username' },
  { id: 'email', name: 'Email', icon: '📧', color: '#EA4335', bgColor: '#fee2e2', baseUrl: 'mailto:', placeholder: 'email@example.com' },
  { id: 'website', name: 'Website', icon: '🌐', color: '#6366F1', bgColor: '#ede9fe', baseUrl: 'https://', placeholder: 'yourwebsite.com' },
  { id: 'amazon', name: 'Amazon Store', icon: '📦', color: '#FF9900', bgColor: '#fef3c7', baseUrl: 'https://amazon.com/s?k=', placeholder: 'store name' },
  { id: 'alibaba', name: 'Alibaba', icon: '🏪', color: '#FF6A00', bgColor: '#fed7aa', baseUrl: 'https://alibaba.com/trade/', placeholder: 'store' },
  { id: 'etsy', name: 'Etsy', icon: '🎨', color: '#F45800', bgColor: '#fed7aa', baseUrl: 'https://etsy.com/shop/', placeholder: 'shopname' },
  { id: 'daraz', name: 'Daraz', icon: '🛍️', color: '#F85606', bgColor: '#fed7aa', baseUrl: 'https://daraz.pk/', placeholder: 'shop' },
];

export const GLOBAL_REGIONS = [
  { name: 'Pakistan', flag: '🇵🇰', code: 'PK', currency: 'PKR', dial: '+92' },
  { name: 'China', flag: '🇨🇳', code: 'CN', currency: 'CNY', dial: '+86' },
  { name: 'Bangladesh', flag: '🇧🇩', code: 'BD', currency: 'BDT', dial: '+880' },
  { name: 'Turkey', flag: '🇹🇷', code: 'TR', currency: 'TRY', dial: '+90' },
  { name: 'India', flag: '🇮🇳', code: 'IN', currency: 'INR', dial: '+91' },
  { name: 'USA', flag: '🇺🇸', code: 'US', currency: 'USD', dial: '+1' },
  { name: 'UAE', flag: '🇦🇪', code: 'AE', currency: 'AED', dial: '+971' },
  { name: 'UK', flag: '🇬🇧', code: 'GB', currency: 'GBP', dial: '+44' },
  { name: 'Russia', flag: '🇷🇺', code: 'RU', currency: 'RUB', dial: '+7' },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', currency: 'SAR', dial: '+966' },
  { name: 'Germany', flag: '🇩🇪', code: 'DE', currency: 'EUR', dial: '+49' },
  { name: 'France', flag: '🇫🇷', code: 'FR', currency: 'EUR', dial: '+33' },
  { name: 'Korea', flag: '🇰🇷', code: 'KR', currency: 'KRW', dial: '+82' },
  { name: 'Afghanistan', flag: '🇦🇫', code: 'AF', currency: 'AFN', dial: '+93' },
  { name: 'Iran', flag: '🇮🇷', code: 'IR', currency: 'IRR', dial: '+98' },
];
